

image: node:10.15.0
pipelines:
  default:
    - step:
        script:
          - COMMIT=$(git rev-parse --short HEAD)
          - IMAGE_NAME="argocdapp:${COMMIT}"
          - echo ${COMMIT} > commit.txt
          - npm install
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build . -t ${IMAGE_NAME}
          - docker push ${IMAGE_NAME}
        services:
          - docker